baseURL = "https://jpata.github.io"
title = "Joosep Pata"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Joosep Pata"
  description = "Senior Research Scientist in Applied Machine Learning"
  avatarURL = "/img/avatar-icon.png"
  AvatarAltText = "avatar"
  avatarSize = "size-l"
  ShowBackToTopButton = true # true or false for "back to top" button on posts and pages
  socialIcons = [
    {name = "github", url = "https://github.com/jpata"},
    {name = "linkedin", url = "https://linkedin.com/in/joosep-pata"},
    {name = "email", url = "mailto:joosep.pata@gmail.com"}
  ]
  accentColor = "#FF4D4D"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Research"
    pre = "<span data-feather='code'></span>"
    url = "/page/research/"
    weight = 2

  [[menu.main]]
    name = "Updates"
    pre = "<span data-feather='book'></span>"
    url = "/updates/"
    weight = 3

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
